### ISSUE TITLE
DomainNet dataset.

### ISSUE THREAD

**Issue by Dyb3438** [BIT-DA/RoTTA#3]
Hey Longhui,

I am happy to see you release the code of CIFAR10 and CIFAR100 datasets, but there is still a little pity that I cannot see the implementation in DomainNet dataset, which is mentioned in your paper. Could you release the code of DomainNet dataset soon? Or could you tell me how to implement it based on the existing code.

Best.
Yongyi

**Comment by yuanlonghui** [comment]
Thank you very much for your interest. However, regrettably, I do not plan to open source the code of DomainNet, primarily due to considerations of my own research plan. I hope you can understand. But you can treat each domain of DomainNet as a type of corruption like CIFAR10/100-C and implement it by yourself.
